# version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    # env_file:
    #   - .env
    env_file:
      - /root/Digital-Ocean-Test/backend/.env
      # - ./backend/.env
    volumes:
      - ./backend/media:/app/media # база данных
      - ./backend/db.sqlite3:/app/db.sqlite3
      - ./backend/staticfiles:/app/staticfiles
    ports:
      - "8001:8001"
    # depends_on:
    #   - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    env_file:
      - /root/Digital-Ocean-Test/frontend/.env.local
      # - ./frontend/.env.local
      #для доккер разработки 
    environment:
      - DOCKER=1
    ports:
      - "3000:3000"
    depends_on:
      - backend
  # db:
  #   image: postgres:16
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER:-postgres}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  #     POSTGRES_DB: ${POSTGRES_DB:-mydb}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5433:5432"

volumes:
  postgres_data:
